name: Trigger auto deployment for inventory-management-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/inventory-management-api-AutoDeployTrigger-8f2f2d6c-7308-497a-a99e-60fbe75b6e69.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.INVENTORYMANAGEMENTAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.INVENTORYMANAGEMENTAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.INVENTORYMANAGEMENTAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.INVENTORYMANAGEMENTAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.INVENTORYMANAGEMENTAPI_REGISTRY_PASSWORD }}
          containerAppName: inventory-management-api
          resourceGroup: rg-inventory-management-api
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


